name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: FTP Deploy Locaweb
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ftp.profgustavomacedo.com
          user: profgustavomaced1
          password: Consultor@4021
          server-dir: /home/profgustavomaced1/
